---
title: "Bootstrapping"
author: "Andy Turner"
date: "2023-11-16"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(modelr)

set.seed(1)
```

## Generate a relevant example

```{r}
n_samp = 250

sim_df_const= 
  tibble(
    x= rnorm(n_samp, 1, 1),
    error= rnorm(n_samp, 0, 1), 
    y = 2 + 3 * x + error
  )

sim_df_nonconst=
  sim_df_const |> 
  mutate(error= error *.76 * x,
         y= 2 + 3 * x + error)
  

sim_df_const |> 
  ggplot(aes(x=x, y=y))+ geom_point()

sim_df_nonconst |> 
  ggplot(aes(x= x, y=y))+ geom_point()
```

fit some linear models

```{r}
sim_df_const |> 
  lm(y~x, data= _) |> 
  broom::tidy()

sim_df_nonconst |> 
  lm(y~x, data=_) |> 
  broom::tidy()
```

## Draw and analyze a bootstrap sample

Start with a little function 

```{r}
boot_strap = function(df) {
  
  sample_frac(df, replace= TRUE)
}
```

Let's see how this works

```{r}
sim_df_nonconst |> 
  boot_strap() |> 
  ggplot(aes(x=x, y=y))+
  geom_point(alpha=0.5)+ 
  stat_smooth(method = "lm")
```


